#!/usr/bin/env python3
"""
render/sync_protocol.py

Keep the *volatile facts* in the protocol doc in sync with the single source of
truth, so the prose can't silently drift from the fielded instrument again.

The protocol ("SARA USA — Survey Protocol v10.md") is context/reasoning only —
per CLAUDE.md it must NOT restate item text, scales, or the live/cut split. But
its worked examples inevitably quote a few of those values (the expert anchors,
the tolerability scale, which Method-3 items are live vs cut). Those are the
bits that rot. This script regenerates *only* those bits, inside HTML-comment
markers, from:

  - survey/sara_usa.md          (item text + scales + dumpster — via spec_loader)
  - survey/sara/__init__.py     (COMPARATORS / SANITY_ACTS randomisation pools)

Everything outside the markers — the "why", the pedagogy — stays hand-written.

Markers in the protocol look like:

    <!-- BEGIN:auto:experts (generated by render/sync_protocol.py — edit the instrument, not here) -->
    ...generated...
    <!-- END:auto:experts -->

Usage:
    python3 render/sync_protocol.py            # rewrite the protocol in place
    python3 render/sync_protocol.py --check    # exit 1 if any block is stale (CI/make)

The item->block mapping below is a protocol-authoring decision (the instrument
doesn't tag items by method), so it lives here, explicitly.
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "survey"))
try:
    from spec_loader import load_spec
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
MD_INSTRUMENT = os.path.join(REPO_ROOT, "survey", "sara_usa.md")
APP_INIT = os.path.join(REPO_ROOT, "survey", "sara", "__init__.py")
PROTOCOL = os.path.join(REPO_ROOT, "SARA USA — Survey Protocol v10.md")

# Which instrument items back each Method's worked example (authoring decision).
EXPERT_IDS = ["m2_experts_lecun", "m2_experts_fri_super",
              "m2_experts_fri_domain", "m2_experts_amodei"]
METHOD3_LIVE = [("Standards", "m3a_i_standards"), ("Sanity anchor", "m3_sanity")]
METHOD3_CUT = ["m3a_ii_safety", "m2_frame_applicable"]

# The prefix group captures any blockquote/indent markers ("> ", "  ") that sit
# in front of the BEGIN marker on its line, so generated lines can be re-prefixed
# to match — worked examples in the protocol are blockquotes.
BLOCK_RE = re.compile(
    r"(?P<prefix>[ \t>]*)(?P<begin><!--\s*BEGIN:auto:(?P<key>[\w-]+)\b.*?-->)"
    r"(?P<body>.*?)"
    r"(?P<end><!--\s*END:auto:(?P=key)\s*-->)",
    re.DOTALL,
)


# ── helpers ─────────────────────────────────────────────────────────────

def _flat(text):
    """Collapse a folded-YAML string to a single clean line."""
    return " ".join((text or "").split())


def _scale_text(spec, item):
    """Human-readable ' / '-joined response options for an item."""
    scales = spec.get("scales", {})
    name = item.get("scale")
    if name and name in scales:
        return " / ".join(scales[name]["labels"])
    if item.get("options"):
        return " / ".join(str(o) for o in item["options"])
    if item.get("widget") == "number":
        return "(numeric entry)"
    return "(no fixed scale)"


def _find_live(spec, item_id):
    for page in spec.get("pages", []):
        for it in page.get("items") or []:
            if it.get("id") == item_id:
                return it
    return None


def _find_dumpster(spec, item_id):
    for entry in spec.get("dumpster") or []:
        for it in entry.get("items") or []:
            if it.get("id") == item_id:
                return it
    return None


def _read_list(varname):
    """Pull a simple string-list literal (COMPARATORS/SANITY_ACTS) out of the
    oTree app source, without importing oTree."""
    src = open(APP_INIT, encoding="utf-8").read()
    m = re.search(varname + r"\s*=\s*\[(.*?)\]", src, re.DOTALL)
    if not m:
        return []
    return [a or b for a, b in
            re.findall(r'"([^"]*)"|\'([^\']*)\'', m.group(1))]


# ── block generators (return the inner body, no markers) ────────────────

def gen_tolerability_scale(spec):
    labels = spec["scales"]["tolerability2"]["labels"]
    return "**" + "** vs **".join(_flat(l) for l in labels) + "**"


def gen_ladder_scale(spec):
    labels = spec["scales"]["ladder9"]["labels"]
    return " / ".join(_flat(l) for l in labels)


def gen_experts(spec):
    items = [_find_live(spec, i) for i in EXPERT_IDS]
    items = [it for it in items if it]
    if not items:
        return "_(no expert items found in the instrument)_"
    scale = _scale_text(spec, items[0])
    lines = ["The named-source items, judged within-person and reported by "
             "source (text verbatim from the instrument):", ""]
    for n, it in enumerate(items, 1):
        lines.append("%d. %s" % (n, _flat(it["text"])))
    lines.append("")
    lines.append("_Each judged on:_ %s" % scale)
    return "\n".join(lines)


def gen_method3_live(spec):
    comparators = _read_list("COMPARATORS")
    sanity = _read_list("SANITY_ACTS")
    lines = ["Live comparator items (text verbatim; `{comparator}` / `{sanity}` "
             "are filled per respondent):", ""]
    for label, item_id in METHOD3_LIVE:
        it = _find_live(spec, item_id)
        if not it:
            lines.append("- **%s** (`%s`): _(missing from instrument)_" % (label, item_id))
            continue
        lines.append("- **%s** (`%s`): %s" % (label, item_id, _flat(it["text"])))
        lines.append("  _Scale:_ %s" % _scale_text(spec, it))
    lines.append("")
    lines.append("Comparator pool (`survey/sara/__init__.py`): %s"
                 % (" / ".join(comparators) or "_(none)_"))
    lines.append("")
    lines.append("Sanity-activity pool: %s" % (" / ".join(sanity) or "_(none)_"))
    return "\n".join(lines)


def gen_method3_cut(spec):
    lines = ["Retired to the dumpster (recoverable — see the instrument's "
             "`dumpster:` key):", ""]
    for item_id in METHOD3_CUT:
        it = _find_dumpster(spec, item_id)
        if not it:
            lines.append("- `%s`: _(not currently in the dumpster)_" % item_id)
            continue
        lines.append("- `%s`: %s" % (item_id, _flat(it["text"])))
    return "\n".join(lines)


GENERATORS = {
    "tolerability-scale": gen_tolerability_scale,
    "ladder-scale": gen_ladder_scale,
    "experts": gen_experts,
    "method3-live": gen_method3_live,
    "method3-cut": gen_method3_cut,
}


# ── driver ──────────────────────────────────────────────────────────────

def main(argv):
    check = "--check" in argv[1:]
    spec = load_spec(MD_INSTRUMENT)
    doc = open(PROTOCOL, encoding="utf-8").read()

    seen = set()
    stale = []

    def replace(m):
        key = m.group("key")
        seen.add(key)
        gen = GENERATORS.get(key)
        if gen is None:
            print("  warning: no generator for auto:%s — left untouched" % key,
                  file=sys.stderr)
            return m.group(0)
        prefix = m.group("prefix")           # e.g. "> " inside a blockquote, else ""
        pad = prefix.rstrip()                # bare "> " → ">" for blank quoted lines
        lines = gen(spec).rstrip("\n").split("\n")
        quoted = [(prefix + ln).rstrip() if ln.strip() else pad for ln in lines]
        new_body = "\n" + pad + "\n" + "\n".join(quoted) + "\n" + pad + "\n" + prefix
        if m.group("body") != new_body:
            stale.append(key)
        return prefix + m.group("begin") + new_body + m.group("end")

    new_doc = BLOCK_RE.sub(replace, doc)

    missing = [k for k in GENERATORS if k not in seen]
    if missing:
        print("  note: generators with no marker in the protocol: %s"
              % ", ".join(sorted(missing)), file=sys.stderr)

    if check:
        if stale:
            print("STALE: these auto-blocks are out of date with the instrument: %s"
                  % ", ".join(sorted(set(stale))), file=sys.stderr)
            print("Run:  python3 render/sync_protocol.py", file=sys.stderr)
            return 1
        print("Protocol auto-blocks are in sync with the instrument.")
        return 0

    if new_doc != doc:
        open(PROTOCOL, "w", encoding="utf-8").write(new_doc)
        print("Updated %d auto-block(s) in the protocol: %s"
              % (len(set(stale)), ", ".join(sorted(set(stale)))))
    else:
        print("Protocol already in sync — nothing to write.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
