#!/usr/bin/env python3
"""
render/sync_protocol.py

Keep the *volatile facts* in the protocol doc in sync with the single source of
truth, so the prose can't silently drift from the fielded instrument again.

The protocol ("SARA USA — Survey Protocol v10.md") is context/reasoning only —
per CLAUDE.md it must NOT restate item text or scales. But its worked examples
inevitably quote a few of those values (the expert anchors, the live Method-3
comparator items, the ladder rungs). Those are the bits that rot. This script
regenerates *only* those bits, inside HTML-comment markers, from:

  - survey/sara_usa.md          (item text + scales + dumpster — via spec_loader)

Everything outside the markers — the "why", the pedagogy — stays hand-written.

Markers in the protocol look like:

    <!-- BEGIN:auto:experts (generated by render/sync_protocol.py — edit the instrument, not here) -->
    ...generated...
    <!-- END:auto:experts -->

Usage:
    python3 render/sync_protocol.py            # rewrite the protocol in place
    python3 render/sync_protocol.py --check    # exit 1 if any block is stale (CI/make)

The item->block mapping below is a protocol-authoring decision (the instrument
doesn't tag items by method), so it lives here, explicitly.

(The comparator/sanity randomisation pools this script once scraped from the
oTree app were retired with their items to the instrument's dumpster; blocks
are now generated from the instrument alone.)
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "survey"))
try:
    from spec_loader import OPT_OUT_LABEL, item_gets_opt_out, load_spec
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
MD_INSTRUMENT = os.path.join(REPO_ROOT, "survey", "sara_usa.md")
PROTOCOL = os.path.join(REPO_ROOT, "SARA USA — Survey Protocol v10.md")

# Which instrument content backs each collapsible "as fielded" block in the
# protocol. Page-based where possible (add an item to the page → it shows up in
# the briefing automatically, no edit here); `ids` names dumpster items
# explicitly.
ITEM_BLOCKS = {
    "ladder-items": dict(
        pages=["severity_ladder"],
        summary="Method 1 — the severity-ladder items, as fielded"),
    "wtp-item": dict(
        ids=["m5_wtp"],
        summary="Method 1 — the willingness-to-pay item, as fielded"),
    "experts": dict(
        pages=["expert_judgement"],
        summary="Method 4 — the named-source items, as fielded"),
    "method3-live": dict(
        pages=["safety_standards"],
        summary="Method 3 — comparator items (incl. the embedded attention "
                "checks), as fielded"),
    "muskan-items": dict(
        pages=["superintelligence_support", "superintelligence_route"],
        summary="Superintelligence module — ban-support DV and ELM route "
                "mediators, as fielded"),
}

# The prefix group captures any blockquote/indent markers ("> ", "  ") that sit
# in front of the BEGIN marker on its line, so generated lines can be re-prefixed
# to match — worked examples in the protocol are blockquotes.
BLOCK_RE = re.compile(
    r"(?P<prefix>[ \t>]*)(?P<begin><!--\s*BEGIN:auto:(?P<key>[\w-]+)\b.*?-->)"
    r"(?P<body>.*?)"
    r"(?P<end><!--\s*END:auto:(?P=key)\s*-->)",
    re.DOTALL,
)


# ── helpers ─────────────────────────────────────────────────────────────

def _flat(text):
    """Collapse a folded-YAML string to a single clean line."""
    return " ".join((text or "").split())


def _scale_text(spec, item):
    """Human-readable ' / '-joined response options for an item, including the
    engine-appended universal opt-out where it applies — the protocol's worked
    examples should show what participants see."""
    scales = spec.get("scales", {})
    name = item.get("scale")
    text = None
    if name and name in scales:
        text = " / ".join(scales[name]["labels"])
    elif item.get("options"):
        text = " / ".join(str(o) for o in item["options"])
    elif item.get("widget") == "number":
        text = "(numeric entry)"
    if text is None:
        return "(no fixed scale)"
    if item_gets_opt_out(item, scales):
        text += " / %s" % OPT_OUT_LABEL
    return text


def _find_live(spec, item_id):
    for page in spec.get("pages", []):
        for it in page.get("items") or []:
            if it.get("id") == item_id:
                return it
    return None


def _find_dumpster(spec, item_id):
    for entry in spec.get("dumpster") or []:
        for it in entry.get("items") or []:
            if it.get("id") == item_id:
                return it
    return None


def _find_page(spec, page_id):
    for page in spec.get("pages", []):
        if page.get("id") == page_id:
            return page
    return None


# ── rendering helpers ───────────────────────────────────────────────────

def _details(summary, body_lines):
    """Wrap generated content in a collapsible <details> block. GitHub renders
    this folded (skimmable) and expandable (shows the real items). The blank
    lines around the body are required for the Markdown inside to render."""
    n = sum(1 for ln in body_lines if ln.startswith("- **`"))
    label = summary + (" — %d item%s" % (n, "" if n == 1 else "s") if n else "")
    return "\n".join(["<details>",
                      "<summary>%s (click to expand)</summary>" % label,
                      ""] + body_lines + ["", "</details>"])


def _item_lines(spec, item, dumpster=False):
    tag = " _(dumpster)_" if dumpster else ""
    lines = ["- **`%s`**%s — %s" % (item["id"], tag, _flat(item["text"]))]
    scale = _scale_text(spec, item)
    if scale and scale != "(no fixed scale)":
        lines.append("  - _Scale:_ %s" % scale)
    return lines


# ── the one generator that backs every collapsible item block ───────────

def gen_item_block(spec, cfg):
    body = []
    for page_id in cfg.get("pages", []):
        page = _find_page(spec, page_id)
        if page is None:
            # Fail loudly: a renamed/removed page would otherwise silently
            # empty this block of the protocol.
            sys.exit("sync_protocol: page %r (auto-block %r) is not in the "
                     "instrument — update ITEM_BLOCKS in render/sync_protocol.py"
                     % (page_id, cfg["summary"]))
        for it in page.get("items") or []:
            body += _item_lines(spec, it)
    for item_id in cfg.get("ids", []):
        it = _find_live(spec, item_id)
        if it:
            body += _item_lines(spec, it)
        else:
            it = _find_dumpster(spec, item_id)
            body += (_item_lines(spec, it, dumpster=True) if it
                     else ["- **`%s`** — _(not found in instrument)_" % item_id])
    if not body:
        body = ["_(no items found)_"]
    return _details(cfg["summary"], body)


# ── the generator registry ──────────────────────────────────────────────

# Marker key → generator. Every block is a collapsible "as fielded" item block,
# data-driven from ITEM_BLOCKS; each item already prints its own scale, so there
# is no separate scale block. (The tolerability scale is short and stable enough
# to be stated inline in the protocol prose rather than generated.)
GENERATORS = {}
for _key, _cfg in ITEM_BLOCKS.items():
    GENERATORS[_key] = (lambda spec, cfg=_cfg: gen_item_block(spec, cfg))


# ── driver ──────────────────────────────────────────────────────────────

def main(argv):
    check = "--check" in argv[1:]
    spec = load_spec(MD_INSTRUMENT)
    doc = open(PROTOCOL, encoding="utf-8").read()

    seen = set()
    stale = []

    def replace(m):
        key = m.group("key")
        seen.add(key)
        gen = GENERATORS.get(key)
        if gen is None:
            print("  warning: no generator for auto:%s — left untouched" % key,
                  file=sys.stderr)
            return m.group(0)
        prefix = m.group("prefix")           # e.g. "> " inside a blockquote, else ""
        pad = prefix.rstrip()                # bare "> " → ">" for blank quoted lines
        lines = gen(spec).rstrip("\n").split("\n")
        quoted = [(prefix + ln).rstrip() if ln.strip() else pad for ln in lines]
        new_body = "\n" + pad + "\n" + "\n".join(quoted) + "\n" + pad + "\n" + prefix
        if m.group("body") != new_body:
            stale.append(key)
        return prefix + m.group("begin") + new_body + m.group("end")

    new_doc = BLOCK_RE.sub(replace, doc)

    missing = [k for k in GENERATORS if k not in seen]
    if missing:
        print("  note: generators with no marker in the protocol: %s"
              % ", ".join(sorted(missing)), file=sys.stderr)

    if check:
        if stale:
            print("STALE: these auto-blocks are out of date with the instrument: %s"
                  % ", ".join(sorted(set(stale))), file=sys.stderr)
            print("Run:  python3 render/sync_protocol.py", file=sys.stderr)
            return 1
        print("Protocol auto-blocks are in sync with the instrument.")
        return 0

    if new_doc != doc:
        open(PROTOCOL, "w", encoding="utf-8").write(new_doc)
        print("Updated %d auto-block(s) in the protocol: %s"
              % (len(set(stale)), ", ".join(sorted(set(stale)))))
    else:
        print("Protocol already in sync — nothing to write.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
